export const types = [
  {
    name: 'normal',
    color: '#A8A878',
    backgroundColor: '#333333',
    darkerColor: '#1F1F1F',
  },
  {
    name: 'fire',
    color: '#F08030',
    backgroundColor: '#F2D1C9',
    darkerColor: '#C4695E',
  },
  {
    name: 'water',
    color: '#6890F0',
    backgroundColor: '#E6F5FF',
    darkerColor: '#4A7DBF',
  },
  {
    name: 'grass',
    color: '#78C850',
    backgroundColor: '#F2FBE0',
    darkerColor: '#63983E',
  },
  {
    name: 'electric',
    color: '#F8D030',
    backgroundColor: '#1E1E21',
    darkerColor: '#19191D',
  },
  {
    name: 'psychic',
    color: '#F85888',
    backgroundColor: '#F1E7FF',
    darkerColor: '#BD5583',
  },
  {
    name: 'fighting',
    color: '#C03028',
    backgroundColor: '#FDF4E3',
    darkerColor: '#8C2620',
  },
  {
    name: 'rock',
    color: '#B8A038',
    backgroundColor: '#EDEDED',
    darkerColor: '#93832B',
  },
  {
    name: 'ground',
    color: '#E0C068',
    backgroundColor: '#FFF1D0',
    darkerColor: '#A58D4E',
  },
  {
    name: 'flying',
    color: '#A890F0',
    backgroundColor: '#F2F2F2',
    darkerColor: '#7D78C7',
  },
  {
    name: 'ice',
    color: '#98D8D8',
    backgroundColor: '#F5FBFF',
    darkerColor: '#6AA9B3',
  },
  {
    name: 'bug',
    color: '#A8B820',
    backgroundColor: '#F7FFEC',
    darkerColor: '#789026',
  },
  {
    name: 'poison',
    color: '#A040A0',
    backgroundColor: '#F1ECFF',
    darkerColor: '#774281',
  },
  {
    name: 'ghost',
    color: '#705898',
    backgroundColor: '#F8F3FF',
    darkerColor: '#584D71',
  },
  {
    name: 'dark',
    color: '#705848',
    backgroundColor: '#F3F3F3',
    darkerColor: '#524F50',
  },
  {
    name: 'steel',
    color: '#B8B8D0',
    backgroundColor: '#E8E8E8',
    darkerColor: '#8B8AA0',
  },
  {
    name: 'fairy',
    color: '#EE99AC',
    backgroundColor: '#FDF2F8',
    darkerColor: '#CB748C',
  },
  {
    name: 'dragon',
    color: '#7038F8',
    backgroundColor: '#F5F8FF',
    darkerColor: '#482E96',
  },
];
